import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'
import { Resend } from 'resend'
import { generateVehicleStatusExcel } from '@/lib/excel-vehicle-status'

export async function POST(request: NextRequest) {
  const resend = new Resend(process.env.RESEND_API_KEY)
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll() {},
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
  }

  const serviceClient = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  const [{ data: profile }, { data: access }] = await Promise.all([
    serviceClient.from('profiles').select('is_admin, display_id, email').eq('id', user.id).single(),
    serviceClient.from('user_apps').select('id').eq('user_id', user.id).eq('app_slug', 'fleet').limit(1),
  ])

  if (!profile?.is_admin && (!access || access.length === 0)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  if (!profile?.email) {
    return NextResponse.json({ error: 'No email present on user setup. Please contact system admin.' }, { status: 400 })
  }

  const { vehicles, filters } = await request.json()

  if (!vehicles || !Array.isArray(vehicles)) {
    return NextResponse.json({ error: 'vehicles array is required.' }, { status: 400 })
  }

  try {
    const buffer = await generateVehicleStatusExcel(vehicles, filters)
    const date = new Date().toISOString().slice(0, 10)
    const filename = `Vehicle_Status_${date}.xlsx`

    const { error: sendError } = await resend.emails.send({
      from: process.env.NOTIFY_FROM_EMAIL!,
      to: profile.email,
      subject: `Vehicle Status Report — ${new Date().toLocaleDateString('en-GB')}`,
      html: `<p>Please find attached the Vehicle Status report.</p><p>Generated by ${profile.display_id ?? 'GS Apps'} on ${new Date().toLocaleDateString('en-GB')}.</p>`,
      attachments: [
        {
          filename,
          content: buffer.toString('base64'),
        },
      ],
    })

    if (sendError) {
      console.error('Email send error:', sendError)
      return NextResponse.json({ error: 'Failed to send email.' }, { status: 500 })
    }

    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error('Email report error:', err)
    return NextResponse.json({ error: 'Failed to generate and send report.' }, { status: 500 })
  }
}
